In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib notebook

In [2]:
import os
os.chdir('../')

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import random
from src.dataset import *
from src.concept_vectors import *
from src.util import *
from src.plots import *
from src.hierarchy import *
from src.metrics import *
from src.models import * 

2023-02-09 18:18:16.309477: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from PIL import Image, ImageOps
import pickle
import sklearn

In [9]:
dataset = CUB_Dataset()

In [30]:
for suffix in ["","_image_robustness","_model_responsiveness"]:
    print(np.sum(load_label_vectors_simple(dataset.get_attributes()[0],dataset,suffix,42)))

407
447
407


In [63]:
train_VAE(dataset,"",42,save_location="", latent_dim=2,epochs=1,concept_alignment=True)

Latent dim 112


/auto/homes/njr61/main_code/src/models.py:228: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  images = np.array([file_to_numpy(i) for i in all_files])


1/1 [==============================] - 2s 2s/step - loss: 5678.0908 - reconstruction_loss: 2838.9517 - kl_loss: 0.1575 - concept_loss: 2838.9819


/auto/homes/njr61/main_code/src/models.py:266: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  all_images = resize_cub(np.array(all_images))


1/1 [==============================] - 0s 227ms/step


In [65]:
load_vae_vectors_simple("has_back_color::black",CUB_Dataset(),"_image_responsiveness",seed=42)

array([[-0.67367435,  0.2746278 ]], dtype=float32)

In [70]:
load_vae_concept_vectors_simple("has_back_color::black",CUB_Dataset(),"",seed=42)

array([[ 1.1396388 ,  0.19243965, -0.42658675,  0.01701454, -0.32708898,
         0.7208395 ,  0.38758543,  0.07034683,  0.21086532,  0.5162337 ,
         0.37147635, -0.01094094, -0.21870965,  0.45760262, -0.27087864,
        -0.00768346, -0.66996974,  0.14430285, -0.43691167, -0.85338527,
         0.06586748, -0.22222969, -0.3834473 , -0.6014196 , -0.4063005 ,
         0.45655298, -0.00275847, -0.18300647,  0.19964525, -0.69305444,
         0.37549675, -0.5941823 , -0.61327386, -0.11705576, -0.09494688,
        -0.10341191, -0.09245952,  0.31608596,  0.02900577, -0.53867567,
        -0.2669893 ,  0.16547063, -0.44882005, -0.27444395, -0.03798074,
        -0.15899993,  0.5672046 , -0.67011654, -0.17625827,  0.61872476,
         0.3530683 , -0.44659752, -0.12664387, -0.9338273 , -0.333057  ,
        -0.2857629 ,  0.21944374, -0.06597994,  0.26274833,  0.25763166,
         0.19009157, -0.10071413, -0.25036108, -0.73016727,  0.0170529 ,
        -0.23975375, -0.6254666 ,  0.5353975 ,  0.1

In [74]:
create_concept2vec(dataset,"_image_robustness",42)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/CUB_ige_robustness/preprocessed/train.pkl'

In [76]:
load_concept2vec_vectors_simple(dataset.get_attributes()[0],dataset,"",42)

array([[-0.08862728, -0.22278228, -0.33395338,  0.3019868 , -0.01222411,
         0.29873982,  0.35323834,  0.1366382 , -0.25656658,  0.324455  ,
         0.17890984, -0.32997307, -0.01974672, -0.2481588 , -0.2735666 ,
         0.2445152 ,  0.15376762,  0.3406197 ,  0.02418177, -0.03433285,
         0.26493436, -0.0081104 ,  0.28707227, -0.31152803, -0.20898055,
        -0.19636793, -0.23137163,  0.26689827,  0.21054439,  0.27037305,
         0.14287092, -0.04401413]], dtype=float32)

In [12]:
create_model_vectors(dataset.get_attributes()[0:1],dataset,"_image_robustness",42)

In [14]:
create_tcav_dataset(dataset.get_attributes()[0],CUB_Dataset(),
                            2,10,
                            seed=42,suffix="_image_robustness",model_name="VGG16",bottlenecks=['block4_conv1'])

INFO:tensorflow:block4_conv1 ['has_bill_shape::dagger', 'random500_0'] zebra 0.1
INFO:tensorflow:block4_conv1 ['has_bill_shape::dagger', 'random500_1'] zebra 0.1
INFO:tensorflow:block4_conv1 ['random500_0', 'random500_1'] zebra 0.1
INFO:tensorflow:block4_conv1 ['random500_1', 'random500_0'] zebra 0.1
INFO:tensorflow:TCAV will 4 params
INFO:tensorflow:block4_conv1 ['has_bill_shape::dagger', 'random500_0'] zebra 0.1
INFO:tensorflow:block4_conv1 ['has_bill_shape::dagger', 'random500_1'] zebra 0.1
INFO:tensorflow:running 2 params
INFO:tensorflow:Running param 0 of 2
INFO:tensorflow:running zebra ['has_bill_shape::dagger', 'random500_0']
INFO:tensorflow:./results/activations/acts_has_bill_shape::dagger_block4_conv1 does not exist, Making one...
INFO:tensorflow:Loaded ./results/activations/acts_random500_0_block4_conv1 shape (50, 28, 28, 512)
INFO:tensorflow:Loaded ./results/activations/acts_zebra_block4_conv1 shape (5, 28, 28, 512)
INFO:tensorflow:Training CAV ['has_bill_shape::dagger', 'ra

In [15]:
embedding_method = combine_embeddings_concatenate(load_label_vectors_simple,load_tcav_vectors_simple)

In [17]:
embedding_method(dataset.get_attributes()[0],CUB_Dataset(),"_image_robustness",42)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [115]:
load_label_vectors_simple(dataset.get_attributes()[0],dataset,"_model_robustness",42)

array([[0, 0, 0, ..., 0, 0, 0]])

In [18]:
for seed in [43,44,45]:
    for suffix in ["","_image_robustness","_image_responsiveness",
                   "_model_robustness","_model_responsiveness"]:
        create_concept2vec(CUB_Dataset(),suffix,seed)

2023-02-08 11:44:44.117393: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


500/500 [==============================] - 7s 14ms/step - loss: 0.5529


In [23]:
train_VAE(CUB_Dataset(),"_model_robustness",43,epochs=1,latent_dim=4,concept_alignment=True)

(500, 370, 3)
1/1 [==============================] - 10s 10s/step - loss: 5678.7134 - reconstruction_loss: 2839.3328 - kl_loss: 0.1664 - concept_loss: 2839.2141


KeyboardInterrupt: 

In [25]:
seed = 43
suffix = "_image_responsiveness"
dataset = CUB_Dataset()

In [ ]:
all_data = dataset.get_data(seed=seed,suffix=suffix)
all_files = ['dataset/'+i['img_path'] for i in all_data]
images = np.array([file_to_numpy(i) for i in all_files])

In [ ]:
[all_files[i] for i in range(len(images)) if len(images[i].shape) != 3]

In [12]:
len(images[0].shape)

3

In [7]:
c = np.array([tf.image.resize(i,(64,64)) for i in images])

2023-02-09 18:21:05.021133: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-09 18:21:05.030844: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


ValueError: 'images' must have either 3 or 4 dimensions.

In [15]:
data = ['dataset/CUB{}/images/CUB_200_2011/images/093.Clark_Nutcracker/Clark_Nutcracker_0020_85099.jpg', 
        'dataset/CUB{}/images/CUB_200_2011/images/063.Ivory_Gull/Ivory_Gull_0040_49180.jpg', 
        'dataset/CUB{}/images/CUB_200_2011/images/066.Western_Gull/Western_Gull_0002_54825.jpg', 
        'dataset/CUB{}/images/CUB_200_2011/images/025.Pelagic_Cormorant/Pelagic_Cormorant_0022_23802.jpg']

In [20]:
a = Image.open('dataset/CUB_image_robustness/images/CUB_200_2011/images/093.Clark_Nutcracker/Clark_Nutcracker_0020_85099.jpg')

In [21]:
np.array(a).shape

(500, 500, 3)

In [19]:
for suffix in ["","_image_robustness","_image_responsiveness"]:
    for data_point in data:
        img_loc = data_point.format(suffix)
        a = Image.open(img_loc)
        a = a.convert("RGB")
        a.save(img_loc)

In [42]:
create_model_vectors(CUB_Dataset().get_attributes()[0:1],CUB_Dataset(),"",43)

In [47]:
attributes = CUB_Dataset().get_attributes()
attributes = ['"{}"'.format(i) for i in attributes]
print(" ".join(attributes))

"has_bill_shape::dagger" "has_bill_shape::hooked_seabird" "has_bill_shape::all-purpose" "has_bill_shape::cone" "has_wing_color::brown" "has_wing_color::grey" "has_wing_color::yellow" "has_wing_color::black" "has_wing_color::white" "has_wing_color::buff" "has_upperparts_color::brown" "has_upperparts_color::grey" "has_upperparts_color::yellow" "has_upperparts_color::black" "has_upperparts_color::white" "has_upperparts_color::buff" "has_underparts_color::brown" "has_underparts_color::grey" "has_underparts_color::yellow" "has_underparts_color::black" "has_underparts_color::white" "has_underparts_color::buff" "has_breast_pattern::solid" "has_breast_pattern::striped" "has_breast_pattern::multi-colored" "has_back_color::brown" "has_back_color::grey" "has_back_color::yellow" "has_back_color::black" "has_back_color::white" "has_back_color::buff" "has_tail_shape::notched_tail" "has_upper_tail_color::brown" "has_upper_tail_color::grey" "has_upper_tail_color::black" "has_upper_tail_color::white" "